# DeepResearch Environment Configuration
# This environment allows agents to search the web, fetch content, and answer research questions

# Default settings required by HUD VF Gym
defaults:
  max_turns: 5  # Maximum number of turns before timeout
  max_tokens: 512  # Maximum tokens per response

system_prompt: |
  You are an AI research assistant that can search the web and fetch content to answer questions.
  
  You have access to the following tools. You must wrap your tool calls in <tool> tags as shown in the usage examples or else the tool will not be called:
  
  - search(query): Search the web for information
    Usage: <tool>search("your search query")</tool>
    Returns a list of results with titles and URLs
  
  - fetch(url): Fetch and read content from a specific URL
    Usage: <tool>fetch("https://example.com/article")</tool>
    Returns the text content from the webpage
  
  - answer(response): Submit your final answer to the research question
    Usage: <tool>answer("Your researched answer here")</tool>
    
  - done(): Signal that you have completed the task
    Usage: <tool>done()</tool>
  
  You must wrap your tool calls in <tool> tags. You must call <tool>answer("Your researched answer here")</tool> with your final answer when you have finished your research. You must call done() when you have finished your research and you have called <tool>search("your search query")</tool>. Do not emit thinking or reasoning tokens. Provide only your final answer, no other text. For example if the question is "What is the capital of France?", you must call <tool>answer("Paris")</tool> with only Paris, no other text. A common and reliable pattern is to call search() with the exact question as the search query then fetch() with the most promising URLs. Keep in mind you can only call one tool at a time and must wait for the tool to return before calling the next tool.

# Job configuration for HUD tracking
job:
  name: "DeepResearch Agent Run"
  metadata:
    environment: "deepresearch"
    experiment: "web-research"
    version: "1.0"

# Parser configuration
parser:
  use_thinking: false
  xml_weight: 0.6       # Weight for XML format validation
  action_weight: 0.4    # Weight for action syntax validation

# Action mappings from agent tools to MCP tools
action_mappings:
  # Basic search - maps to MCP search with default max_results
  search:
    _parser:
      positional: ["query"]
    _tool: "search"
    query:
      from_arg: "query"
    max_results:
      static: 5
  
  # Basic fetch - maps to MCP fetch with default max_length
  fetch:
    _parser:
      positional: ["url"]
    _tool: "fetch"
    url:
      from_arg: "url"
    max_length:
      static: 2500
  
  # Submit answer
  answer:
    _parser:
      positional: ["response"]
    _tool: "answer"
    final_answer:
      from_arg: "response"

# Rubric configuration for reward calculation
rubric:
  weights:
    task_completion: 0.7      # Correct answer submission
    tool_execution: 0.15      # Successful tool usage
    format_compliance: 0.15   # Proper XML format and syntax